### ISSUE TITLE
Добавить кнопку "открыть" на сайте

### ISSUE THREAD

**Issue by snooppr** [bakhirev/assayo#2]
> Перетащите файл log.txt на эту страницу https://assayo.jp/demo/

На гаджетах этот финт не провернуть в мобильных браузерах, а на Android git прекрасно работает в среде Termux в т.ч. "log.txt" создается.

Добавить кнопку "открыть" на страницу:
https://assayo.jp/demo/
чтобы можно было анализировать проекты с мобильных устройств.

<details>
<summary>спойлер: Android/Termux/Git ---> log.txt</summary>

![Screenshot_20231018-221023_Termux](https://github.com/bakhirev/assayo/assets/61022210/e4693da5-0cdd-44b8-80ab-87d922ba0719)
</details>

**Comment by bakhirev** [comment]
Понял, возьму в доработку. В целом в след. версии мобильное отображение будет улучшено. Например, вместо таблиц будут так же карточки, чтобы уместить все на экран.
