### ISSUE TITLE
[Bug?] Invalid currency code once switched to EUR

### ISSUE THREAD

**Issue by loremus** [bakhirev/assayo#27]
First of all, thank you for creating this wonderful tool. I discovered it today and was surprised by how under-the-radar it is. You guys deserve more recognition for this fantastic work!

A small issue so far: after setting the employee salary currency to EUR and saving it, the entire app turned into a white screen. Below is a screenshot of what happens after each restart:

![image](https://github.com/bakhirev/assayo/assets/68288461/1819d595-81e6-4784-94df-189d50963103)

_P.S._ I would be glad to help with translation to English and French, but I’m not sure where to start. Any guidance would be appreciated!

**Comment by bakhirev** [comment]
Thank you for choosing this app! We are already starting to work on a fix ^_^

**Comment by bakhirev** [comment]
![bug](https://github.com/bakhirev/assayo/assets/2678592/6d135a4c-2770-4d3c-81d2-c0c69be4ac2f)

Please check fix. Since each country has different salaries, the salary is now stored in US dollars and converted at the time of display.
