### ISSUE TITLE
Добавить строку фильтрации в список пользователей

### ISSUE THREAD

**Issue by f0def** [bakhirev/assayo#47]
Enhancement

Сейчас используется нативный браузерный компонент.
Не хватает фильтрации, которая бы позволили быстро находить нужного пользователя из сотен людей.
<img width="632" alt="SCR-20240807-jwwb" src="https://github.com/user-attachments/assets/f1acbf49-d8de-4531-a963-1b17f2afa509">

**Comment by bakhirev** [comment]
Готово. Версию на сайте обновил. Docker контейнер обновил. Проверяй.

**Comment by f0def** [comment]
Супер, работает! А можно еще регистро-независимый поиск сделать?

**Comment by bakhirev** [comment]
Готово

**Comment by f0def** [comment]
Работает, спасибо
