### ISSUE TITLE
Порядковый номер и сохранение состояния при сортировке в списке Сотрудников

### ISSUE THREAD

**Issue by f0def** [bakhirev/assayo#48]
Enhancement

1. Сортирую пользователей и хочется понимать на каком месте один из них
2. Перед сортировкой я нажимаю Показать все, но стоит Отсортировать, как это состояние сбрасывается. Хотелось бы его сохранять (видеть всех)

Отметил на картинке для наглядности
![SCR-20240807-jzam](https://github.com/user-attachments/assets/62e4a211-7723-45d2-9c66-a1a082e02f26)

**Comment by bakhirev** [comment]
Готово. Версию на сайте обновил. Docker контейнер обновил. Проверяй.

**Comment by f0def** [comment]
Порядковый номер работает, а с деперсонализацией не понял: включаю ее, иду в список сотрудников, а там по прежнему имена. Как она работает?

**Comment by bakhirev** [comment]
Обновил билд, переименовал в "скрыть персональные данные". Должно быть так:
- вместо настоящих имён должны быть писатели (Пушки, Шекспир, Толстой и т.п.)
- в номерах задач меняется префикс (например с `JIRA-1234` на `AAAAA-1234`)

**Comment by f0def** [comment]
Понял. Работает как придумано. Задачу можно закрыть.
Для инфо, у нас последний это User310
