### ISSUE TITLE
Не обновляется состояние страницы при изменении периода

### ISSUE THREAD

**Issue by f0def** [bakhirev/assayo#50]
Enhancement

Сверху меняю период на интересующий, ожидаю, что данные в таблице актуализируются согласно выбранным датам, но этого не происходит.
Использую обход - перехожу на другую страницу через меню и возвращаюсь обратно. Было бы удобно, если бы этого не требовалось.
<img width="1392" alt="image" src="https://github.com/user-attachments/assets/5b6061e5-5811-40de-9bdd-ea9cba16078b">

**Comment by bakhirev** [comment]
суть: переписать store для фильтров. Каша в методе updateByFilters, вылетают ачивки, не устанавливается новый хэш, как результат не обновляется таблица

**Comment by bakhirev** [comment]
Готово. Версию на сайте обновил. Docker контейнер обновил. Проверяй.

Я заметил, что ты скрываешь имена сотрудников, поэтому в раздел "Настройки" добавил чекбокс "деперсонализация данных". Возможно он облегчит задачу скрытия персональных данных на публичных скриншотах.

**Comment by f0def** [comment]
Класс, порядковый номер появился, огромное спасибо!
