### ISSUE TITLE
Позиция сотрудника по характеристике

### ISSUE THREAD

**Issue by f0def** [bakhirev/assayo#51]
Enhancement

Когда смотришь основные характеристики было бы удобно понимать не только количественное значение, а еще и позицию по этому показателю среди сотрудников. Примерно так:
![image](https://github.com/user-attachments/assets/00915a4d-69b2-4b19-89ef-fdc1a3c5f12f)

**Comment by bakhirev** [comment]
Предварительно: думаю как оптимально сделать. Рассчитывать заранее вроде перебор, но рассчитывать на лету для каждой страницы тоже тормоза будут. По дизайну видимо серым цветом будет

**Comment by bakhirev** [comment]
Пока не выкладывал, показываю прототип.

1. Не хочется перегружать карточку, т.к. кажется что это доп. инфа, которую, возможно, стоит вообще на отдельную страницу вынести. Поэтому добавил небольшой серый блок. Так норм?
2. Так же добавил в общую инфу карточки первый / последний коммит, т.к. кажется что это актуально на большом количестве сотрудников (хз кто работает, а кто уже ушел). Это полезно или только отнимает внимание у основных метрик?

![image](https://github.com/user-attachments/assets/ff664029-79c8-458e-bacd-c362da5f8f20)

**Comment by f0def** [comment]
1. Да
2. Думаю, что менее важно. Я бы вниз их перенес

**Comment by bakhirev** [comment]
1. частично вывел, дорабатываю для других показателей
2. скрыл вообще, буду думать как органично вписать в интерфейс
3. ускорил обработку больших файлов. Анимация теперь стала дерганной, но должно быть существенно быстрее

**Comment by f0def** [comment]
У меня как-то не сходится статистика:
1. Позиция в рейтинге
2. Общее количество
Сравниваю карточку одного сотрудника со списком, отсортированным по количеству коммитов

_Деперсонализация прям огонь 🔥 _
![SCR-20240814-mugf-3](https://github.com/user-attachments/assets/ee0ae5bf-f715-4678-aeb3-2e36e2d77c8a)

**Comment by bakhirev** [comment]
Это не баг, а фича. Какое место должны занять два сотрудника с одинаковым показателем? 

- в первом подходе я подумал об обычном рейтинге: "кто последний достиг, тот и выше". Но в таком случае достаточно починить сортировку в таблице сотрудников и у нас будет просто дублирование информации. Этот путь показался несправедлив. Старичок с такими же заслугами будет ниже новичка.

- во втором подходе я допустил, что если показатель одинаковый, то пользователи займут одну и ту же позицию в рейтинге. На скриншоте видно, что №53 и №54 сделали по 75 коммитов, значат они равноценны. Так же как и все нижние места с одним коммитом. Поэтому и плашка показывает 70 мест (94 - 70 = 24 повтора значения было).

Сбивает с толку? Обычный "игровой" рейтинг один пользователь = одному месту лучше?

**Comment by f0def** [comment]
Думаю, что можно добавить подсказку с этим объяснением. Оставить как сейчас

**Comment by bakhirev** [comment]
Готово. Скорректировал места с учетом флага isStaff, а так же добавил разные направления: 

- первое место за "больше всего задач в день";
- последнее место за "самую большую стоимость одного коммита";
