### ISSUE TITLE
Support for multirepo?

### ISSUE THREAD

**Issue by mihaigalos** [bakhirev/assayo#56]
Hi,

Awesome stuff.
This works well for a monorepo. Any plans to offer support for a multirepo setup?
I tried the following but maybe this is not approach here - doesn't work:

<details><summary>Details</summary>
<p>

```bash
#!/bin/bash

run_for_one_repo(){
  repo=$1
  subfolder="projects/$repo"
  git remote add "$repo" ../"$repo"
  git fetch "$repo"

  # Fetch LFS objects
  git checkout "$repo/main" -- .gitattributes
  git lfs fetch "$repo" --all

  # Using subtree to add and merge preserving full history
  git subtree add --prefix="$subfolder" "$repo/main"
}

# Define the list of repositories
repos=(
 'foo-one'
 'bar-two'
)

git init
git lfs install
for repo in "${repos[@]}"; do
  run_for_one_repo "$repo"
done
```

</p>
</details>

**Comment by bakhirev** [comment]
You need https://github.com/bakhirev/assayo-crawler (or https://hub.docker.com/r/bakhirev/assayo-crawler)
But in this moment I not translated doc on English

**Comment by bakhirev** [comment]
Please let us know if you have managed to solve the problem using Craler service. I'm working on improving it.

**Comment by mihaigalos** [comment]
Hi @bakhirev,

Google Translate works for websites, too. So no language problem. 😄 

I just want to read an input folder containing some subfolders, generate a log which I can then upload to the UI.
Seems thte crawler wants me to create a JSON of where to download from, etc.

I mean I already have the folders and I mount them to the input via docker:

```bash
pushd $(mktemp -d)
docker run --rm -it --name assayo-crawler -p 8091:80 --mount type=bind,source=/Users/foo/projectsNG,destination=/usr/src/assayo_crawler/input --mount type=bind,source=$(pwd),destination=/usr/src/assayo_crawler/output  bakhirev/assayo-crawler
```

**Comment by bakhirev** [comment]
> Seems the crawler wants me to create a JSON of where to download from, etc.
yes

> Can you simplify the crawler to look in the input and create the log without any clicking in the crawler UI?
Yes, i can. But i took this task to work, but not this month. I'm currently editing a python package and making edits from other people and redesigning the site. Maybe in november I'll go back to work on Crawler and do this.

**Comment by bakhirev** [comment]
@mihaigalos special for you, my friend )) Download this txt file.

1. Download [mihaigalos.txt](https://github.com/user-attachments/files/16917337/mihaigalos.txt) in `/Users/foo/mihaigalos.js`
1. Rename `txt` to` js`
2. Run `node mihaigalos.js`
3. You common log was be in `/Users/foo/log.txt`

Script search only one level subdir, If you need recursive - write me. Did that solve the problem?
